version: '3'
services: 
  express:
    container_name: backend 
    build: ./
    restart: always
    ports:
      - "80:5000"
    volumes:
      - "./server:/application/server"
      - "./frontend:/application/frontend"
    environment: 
      - MONGO_PATH=mongodb://database:27017/yurta
    links: 
      - mongo
  mongo-express:
    container_name: mongo-admin
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=database
    ports: 
      - "8081:8081"
    links: 
      - mongo
  mongo:
    container_name: database 
    image: mongo:3.2.0
    ports: 
      - "27100:27017"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock